name: Wyoming moww
version: 0.1.5
slug: wyoming_moww
description: Multi-stage wake word engine (streaming detector + verifier) for Assist
url: https://github.com/darki73/esphome-moww
arch:
  - amd64
  - aarch64
init: false
startup: application
boot: auto
discovery:
  - wyoming
map:
  - share:rw
ports:
  "10400/tcp": 10400
ports_description:
  "10400/tcp": Wyoming protocol
options:
  models_dir: /share/moww
  stage1_cutoff: 0.1
  verifier_cutoff: 0.15
  verifier: true
  save_audio: false
  debug: false
schema:
  models_dir: str
  stage1_cutoff: float(0,1)
  verifier_cutoff: float(0,1)
  verifier: bool
  save_audio: bool
  debug: bool
